# Generated by Django 5.0.6 on 2024-06-21 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_mgn', '0001_initial'),
        ('personnel_mgn', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel_mgn.personnel'),
        ),
        migrations.AddField(
            model_name='demande',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_mgn.client'),
        ),
        migrations.AddField(
            model_name='demande',
            name='créé_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maison',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_mgn.client'),
        ),
        migrations.AddField(
            model_name='maison',
            name='créé_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maisons_crees', to=settings.AUTH_USER_MODEL),
        ),
    ]
