# Generated by Django 5.0.6 on 2024-06-21 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_mgn', '0001_initial'),
        ('personnel_mgn', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plannings', to='customer_mgn.client')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plannings', to='personnel_mgn.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='JourneeDeTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journees', to='planning_mgn.planning')),
            ],
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_present', models.BooleanField(default=True)),
                ('heure_arrivee', models.TimeField(blank=True, null=True)),
                ('heure_depart', models.TimeField(blank=True, null=True)),
                ('remarques', models.TextField(blank=True, null=True)),
                ('journee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='planning_mgn.journeedetravail')),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('statut', models.CharField(max_length=20)),
                ('créé_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_crees', to=settings.AUTH_USER_MODEL)),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning_mgn.planning')),
            ],
        ),
    ]
