# Generated by Django 5.0.6 on 2024-06-21 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_mgn', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_mgn.client')),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('téléphone', models.CharField(max_length=20)),
                ('adresse', models.TextField()),
                ('type_contrat', models.CharField(choices=[('temps plein', 'Temps plein'), ('temps partiel', 'Temps partiel')], max_length=20)),
                ('specialite', models.CharField(max_length=255)),
                ('taux_horaire', models.DecimalField(decimal_places=2, max_digits=6)),
                ('clients', models.ManyToManyField(related_name='personnels', through='personnel_mgn.Affectation', to='customer_mgn.client')),
                ('créé_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnels_crees', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='affectation',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel_mgn.personnel'),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('maison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_mgn.maison')),
            ],
        ),
        migrations.AddField(
            model_name='affectation',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel_mgn.position'),
        ),
    ]
