# Generated by Django 5.0.6 on 2024-06-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel_mgn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='specialite',
            field=models.CharField(choices=[('menagere', 'Ménagère'), ('nounou', 'nounou'), ('assistant', 'assistant'), ('cuisinier', 'cuisinier')], max_length=25),
        ),
    ]
